# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=20)),
                ('billNo', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=10)),
                ('rate', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=10)),
            ],
        ),
    ]
