# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.CharField(default='Null', max_length=15),
        ),
    ]
