# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-21 15:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailID', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('billNo', models.CharField(max_length=10)),
                ('customer', models.CharField(max_length=40)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(max_length=660)),
                ('product', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=14)),
                ('avail', models.DecimalField(decimal_places=10, max_digits=14)),
                ('total', models.DecimalField(decimal_places=10, max_digits=14)),
                ('payment', models.DecimalField(decimal_places=10, max_digits=14)),
                ('description', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=10, max_digits=14)),
                ('duedate', models.DateField()),
                ('mode', models.CharField(max_length=10)),
            ],
        ),
    ]
